Theoretical Questions:

1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it
enhance Python's capabilities for numerical operations?


2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the
other?


3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D
arrays.


4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types
in memory management and performance.


5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?


6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.


7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and
output.


8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various
array dimensions.


9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?


10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array
operations?

###1. Purpose and Advantages of NumPy
Purpose: NumPy is a powerful library for numerical computations in Python. It provides support for arrays, matrices, and a plethora of mathematical functions to operate on these data structures.

Advantages:

Efficiency: NumPy arrays are more efficient in terms of performance and memory usage compared to traditional Python lists.

Convenience: It provides various operations and functions for numerical computations that are both easy to use and highly optimized.

Integration: NumPy seamlessly integrates with other scientific computing libraries such as SciPy, Matplotlib, and Pandas.




2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the
other?

- **`np.mean()`**: Calculates the arithmetic mean without considering weights.
- **`np.average()`**: Calculates the weighted average if weights are provided.
- **Use Case**: Use `np.mean()` for simple averages and `np.average()` when weights are needed.


### 3. Methods for Reversing a NumPy Array
- **1D Array**: `arr[::-1]`
- **2D Array (Flip Rows)**: `arr[::-1, :]`
- **2D Array (Flip Columns)**: `arr[:, ::-1]`

Example:

In [ ]:
import numpy as np
arr_1d = np.array([1, 2, 3, 4, 5])
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
reversed_1d = arr_1d[::-1]
reversed_2d_rows = arr_2d[::-1, :]
reversed_2d_columns = arr_2d[:, ::-1]

## 4. Determine Data Type in a NumPy Array
- **Method**: Use `arr.dtype` to check the data type of elements in a NumPy array.
- **Importance**: Choosing the right data type optimizes memory usage and speeds up computation.

Example:


In [ ]:
import numpy as np

arr = np.array([1, 2, 3])
print(arr.dtype)

int64


###5. ndarrays vs Python Lists And arrays:

Homogeneous: All elements must be of the same type.

Efficient: Optimized for mathematical and numerical computations.

Multi-dimensional: Can create multi-dimensional arrays easily.

Python Lists:

Heterogeneous: Can contain elements of different types.

Less Efficient: Not optimized for numerical computations.

###6. Performance Benefits of NumPy Arrays
Vectorization: NumPy uses highly optimized C and Fortran libraries to perform operations.

Memory Layout: Uses contiguous memory blocks.

Broadcasting: Allows for efficient operations on arrays of different shapes.

### 7. `vstack()` vs. `hstack()`
- **`vstack()`**: Stacks arrays vertically (row-wise).
- **`hstack()`**: Stacks arrays horizontally (column-wise).

Example:



In [ ]:
import numpy as np
arr1 = np.array([1, 2])
arr2 = np.array([3, 4])
result_vstack = np.vstack((arr1, arr2))
result_hstack = np.hstack((arr1, arr2))



8. fliplr() vs flipud()

#fliplr(): Flips the array left to right.

#flipud(): Flips the array upside down.



9. Functionality of `array_split()`
- **Purpose**: Splits an array into multiple sub-arrays.
- **Handling Uneven Splits**: If the array cannot be divided evenly, `array_split()` creates sub-arrays of different sizes.

Example:

In [ ]:

import numpy as np
arr = np.array([1, 2, 3, 4, 5])
splits = np.array_split(arr, 3)

### 10. Vectorization and Broadcasting
##- **Vectorization**: Allows operations on entire arrays without loops, making computations faster.
##- **Broadcasting**: Enables operations on arrays with different shapes by expanding them to compatible shapes.

#Example:

In [ ]:


import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
result = a + b  # Vectorized operation
print (a+b)

[5 7 9]


Practical Questions:
1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.


2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.


3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.


4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.


5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
(uppercase, lowercase, title case, etc.) to each element.


6. Generate a NumPy array of words. Insert a space between each character of every word in the array.


7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.


8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.


9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in
this array.


10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly
averages.

In [17]:
#1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

import numpy as np

# Create a 3x3 array with random integers
array_3x3 = np.random.randint(1, 101, size=(3, 3))
print("Original Array:\n", array_3x3)

# Interchange rows and columns
transposed_array = np.transpose(array_3x3)
print("Transposed Array:\n", transposed_array)

Original Array:
 [[23 20 55]
 [32 95 71]
 [76 76 59]]
Transposed Array:
 [[23 32 76]
 [20 95 76]
 [55 71 59]]


In [19]:
##2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

# Create a 1D array with 10 elements
array_1d = np.arange(10)
print("1D Array:\n", array_1d)

# Reshape to 2x5
array_2x5 = array_1d.reshape((2, 5))
print("2x5 Array:\n", array_2x5)

# Reshape to 5x2
array_5x2 = array_2x5.reshape((5, 2))
print("5x2 Array:\n", array_5x2)

1D Array:
 [0 1 2 3 4 5 6 7 8 9]
2x5 Array:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
5x2 Array:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [18]:
#3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

# Create a 4x4 array with random float values
array_4x4 = np.random.rand(4, 4)
print("4x4 Array:\n", array_4x4)

# Add a border of zeros
array_6x6 = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)
print("6x6 Array with Border:\n", array_6x6)

4x4 Array:
 [[0.68957109 0.10940218 0.38970649 0.89136045]
 [0.98265173 0.14229226 0.27416461 0.14707151]
 [0.25721646 0.7833902  0.14934789 0.74507223]
 [0.83864988 0.35639004 0.34827371 0.43206094]]
6x6 Array with Border:
 [[0.         0.         0.         0.         0.         0.        ]
 [0.         0.68957109 0.10940218 0.38970649 0.89136045 0.        ]
 [0.         0.98265173 0.14229226 0.27416461 0.14707151 0.        ]
 [0.         0.25721646 0.7833902  0.14934789 0.74507223 0.        ]
 [0.         0.83864988 0.35639004 0.34827371 0.43206094 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [21]:
#4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

# Create an array from 10 to 60 with a step of 5
array_step = np.arange(10, 61, 5)
print("Array with Step 5:\n", array_step)

Array with Step 5:
 [10 15 20 25 30 35 40 45 50 55 60]


In [23]:
#5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations.
# Create an array of strings
string_array = np.array(['python', 'numpy', 'pandas'])
print("Original Array:\n", string_array)

# Uppercase
uppercase_array = np.char.upper(string_array)
print("Uppercase:\n", uppercase_array)

# Lowercase
lowercase_array = np.char.lower(string_array)
print("Lowercase:\n", lowercase_array)

# Title case
titlecase_array = np.char.title(string_array)
print("Title Case:\n", titlecase_array)


Original Array:
 ['python' 'numpy' 'pandas']
Uppercase:
 ['PYTHON' 'NUMPY' 'PANDAS']
Lowercase:
 ['python' 'numpy' 'pandas']
Title Case:
 ['Python' 'Numpy' 'Pandas']


In [22]:
#6. Generate a NumPy array of words. Insert a space between each character of every word in the array.
# Create an array of words
words_array = np.array(['hello', 'world'])
print("Original Array:\n", words_array)

# Insert space between characters
spaced_array = np.char.join(' ', words_array)
print("Spaced Array:\n", spaced_array)


Original Array:
 ['hello' 'world']
Spaced Array:
 ['h e l l o' 'w o r l d']


In [24]:
#7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.
# Create two 2D arrays
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

# Element-wise operations
add = np.add(array1, array2)
subtract = np.subtract(array1, array2)
multiply = np.multiply(array1, array2)
divide = np.divide(array1, array2)

print("Addition:\n", add)
print("Subtraction:\n", subtract)
print("Multiplication:\n", multiply)
print("Division:\n", divide)


Addition:
 [[ 6  8]
 [10 12]]
Subtraction:
 [[-4 -4]
 [-4 -4]]
Multiplication:
 [[ 5 12]
 [21 32]]
Division:
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [25]:
#8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.
# Create a 5x5 identity matrix
identity_matrix = np.eye(5)
print("Identity Matrix:\n", identity_matrix)

# Extract diagonal elements
diagonal_elements = np.diag(identity_matrix)
print("Diagonal Elements:\n", diagonal_elements)


Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Diagonal Elements:
 [1. 1. 1. 1. 1.]


In [26]:
#9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.
# Create an array of 100 random integers between 0 and 1000
random_integers = np.random.randint(0, 1001, size=100)
print("Random Integers:\n", random_integers)

# Function to check if a number is prime
def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(np.sqrt(n)) + 1):
        if n % i == 0:
            return False
    return True

# Find prime numbers
prime_numbers = np.array([num for num in random_integers if is_prime(num)])
print("Prime Numbers:\n", prime_numbers)


Random Integers:
 [692 682 765 393 338 391 184 154 141 438 263 848 872 182 570  42 543 153
   4 486 332  25 539 728 749 598 907 870 897 568 391 905 290 934 805 564
 195 688 942 309 728 287 733 244 645 656 488 395 613  81  12 835 389  80
 999 841 669 896 512 826 315 132  90  86 218 276 114 893 272 318 240 725
 927 855 477 790 529 242 918 921 948  46 735 448  80 268 193 597 575 779
  59 227 672 494  95 369 226 680 160 230]
Prime Numbers:
 [263 907 733 613 389 193  59 227]


In [28]:
#10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.
import numpy as np

# Your daily temperatures
daily_temperatures = np.array([34, 37, 30, 25, 27, 34, 35, 34, 38, 36, 27, 22, 24, 28, 29, 22, 27, 38, 22, 26, 35, 33, 22, 21, 37, 30, 27, 34, 21, 24])
print("Daily Temperatures:\n", daily_temperatures)

# Splitting the array into weeks
weekly_splits = np.array_split(daily_temperatures, 5)
print("Weekly Splits:\n", weekly_splits)

# Calculating weekly averages
weekly_averages = [np.mean(week) for week in weekly_splits]
print("Weekly Averages:\n", weekly_averages)



Daily Temperatures:
 [34 37 30 25 27 34 35 34 38 36 27 22 24 28 29 22 27 38 22 26 35 33 22 21
 37 30 27 34 21 24]
Weekly Splits:
 [array([34, 37, 30, 25, 27, 34]), array([35, 34, 38, 36, 27, 22]), array([24, 28, 29, 22, 27, 38]), array([22, 26, 35, 33, 22, 21]), array([37, 30, 27, 34, 21, 24])]
Weekly Averages:
 [31.166666666666668, 32.0, 28.0, 26.5, 28.833333333333332]
